### ISSUE TITLE
remove `trophic_mode_fg` column from dataset?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/fungaltraits#2]
I don't think it's wrong how it's in there, but the structure of funguild data doesn't play well with `spread` and so it's pretty confusing (at least for me) to actually use.  There are also different ways to do the matching and maybe we don't want to choose one for users.  

Suggesting removing it for the sake of simplicity?  

@habacucfm

**Comment by habacucfm** [comment]
@wcornwell  could you elaborate on this a bit more? What does not play well with spread? Yes, there are different ways to do the matching, but then that applies to the way all funguild is match, not only trophic_mode. If trophic_mode gets removed, which is fine, then we should remove the rest of funguild too.

**Comment by wcornwell** [comment]
Yeah I think we should remove all of funguild from the distributed version. Jeff and I were trying to do some analyses of trait by guild and matching was too sparse by `spread`. I think this was because only one-to-one matches were ending up in the same row and it makes most sense to match by genus.  

The other problem is that funguild will change and our data from it will get out of date fast.

**Comment by habacucfm** [comment]
The funguild match is rebuilt every time we remake the DB, it is also matched at the genus level (or at least at some point it was and it easily can be like that). If this is still not what you want, then we could provide a function to download funguild and the user can decide what taxonomic level to use.

**Comment by wcornwell** [comment]
Fundamental problem is that funguild has more than one guild listed for most genera  so matching always will involve some arbitrary choices. That's why I thought to leave that to the user?  Updating is cool though...

**Comment by wcornwell** [comment]
Try making quick plot of any trait by guild from current data.  You'll see what I mean...should be easy but matching issues are annoying

**Comment by wcornwell** [comment]
this is not happening, i think
