### ISSUE TITLE
Install on R version 3.6.3

### ISSUE THREAD

**Issue by vmcgimpsey** [traitecoevo/fungaltraits#4]
Hi,

I tried to install the package ‘fungaltraits’ but keep getting the following error:

ERROR: dependency ‘datastorr’ is not available for package ‘fungaltraits’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/fungaltraits’
Warning messages:
1: package ‘datastorr’ is not available (for R version 3.6.3) 
2: In i.p(...) :
  installation of package ‘/var/folders/1t/j2mgg5pj6d5894p64gv5frvw7_4_jx/T//RtmpfDFGxr/file4f1581f0c38/fungaltraits_0.0.3.tar.gz’ had non-zero exit status

I was wondering if you had a work around?

**Comment by wcornwell** [comment]
hi @vmcgimpsey , have you tried `devtools::install_github("ropenscilabs/datastorr")` ?

**Comment by vmcgimpsey** [comment]
Thanks seems to be resolved. Had to update a few other packages, and restart R. Looking forward to using this tool.
